# Generated by Django 5.2.1 on 2025-05-21 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('join_date', models.DateField()),
                ('data_allocation', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('savings', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='customers_c_name_f018e2_idx'), models.Index(fields=['join_date'], name='customers_c_join_da_3492dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('data_used', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('buy_balance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bill_image', models.ImageField(blank=True, null=True, upload_to='bills/')),
                ('continuous_number', models.CharField(max_length=50, unique=True)),
                ('extra_off', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='customers_a_date_fcc17b_idx'), models.Index(fields=['continuous_number'], name='customers_a_continu_23eda4_idx')],
            },
        ),
    ]
